### ISSUE TITLE
Problems with headings in Firefox

### ISSUE THREAD

**Issue by Izbitzer** [fraywing/textAngular#1236]
Plunker: http://plnkr.co/edit/UjcCqpcI4m09h00oIoUJ

1. Open the provided Plunker in Firefox (I tested with Firefox 47)
2. Click "Edit", this will enable the textAngular editor. 
3. Without writing any text, click the "H1" button. The editor loses focus (unexpected, it does not happen in Chrome)
4. Put focus back in the editor and write something, then press enter. I would expect the editor to leave the "heading mode", but it doesn't. This also works as expected in Chrome.

AngularJS version: 1.5.6
textAngular version: 1.5.2

Notes: I'm using some functionality from https://github.com/fraywing/textAngular/issues/74 to programmatically set focus to the editor. If I remove that code, it seems to behave slightly better, but then it still inserts a line break as soon as I start writing the heading.

**Comment by JoelParke** [comment]
Also I notice that the BOLD button is high-lighted in Firefox after H1 but not in Chrome.

**Comment by Izbitzer** [comment]
I did some investigations into this issue, and it seems that (at least part of) the problem is that when the editor has loaded, running `window.getSelection()` returns the editor `<div>` on Firefox, while on Chrome it returns the `<p>` element inside the `<div>`.

Manually changing the selection before interacting with the editor solves the focus issue, and also that the header state is still active when pressing enter.

It does not affect the issue with BOLD being selected or that a line break is inserted when starting to type.

**Comment by JoelParke** [comment]
The problem with BOLD, is an issue in Firefox which has an error in 'queryCommandState('bold')' which returns bold when header is selected.  We can't fix this directly. The best we could do would be to ignore bold when in the header, but since this is a temporary Firefox issue, it seems best to ignore.

I will do some more investigation to look at your original issue and the focus.

**Comment by JoelParke** [comment]
The new release (SOON) v1.5.3 may help fix this.  I have a partial fix for something else that seems to make this better, but there is another new issue in this same space (with my fix).  Give me a bit to see if I can correct this.  

You can try this already with the current master.  Please let me now what your see. I expect you not to loose focus, but to see a <br> before the header!

**Comment by JoelParke** [comment]
This is fixed with PR #1264.  I will release today.

**Comment by Izbitzer** [comment]
Thanks! I am currently on vacation, so I haven't had a chance to test this, but it sounds promising!

**Comment by JoelParke** [comment]
Yuck, I see that there is still a problem!  So opening this again!

**Comment by JoelParke** [comment]
Please test with v1.5.5 which should resolve this. I will close, and please re-open if this is still an issue!

**Comment by Izbitzer** [comment]
Thanks! It seems to work a lot better, though I still get an extra initial line break when inserting a heading. But maybe that should be filed as a separate issue?
