### ISSUE TITLE
Release 1.4.4 breaks the editor height

### ISSUE THREAD

**Issue by darkmavis1980** [fraywing/textAngular#875]
Just updated to the latest version, and the editor's height now it's only one row by default and it doesn't resize if more than one line of text is entered.

**Comment by andriibuts** [comment]
Some javascript has been added to textAngular.css file so it break all of the styles

**Comment by pbassut** [comment]
Thanks for reporting this. It's fixed now. We'll try to do another release since this is critical

**Comment by darkmavis1980** [comment]
@pbassut thanks for fixing it :-)

**Comment by pbassut** [comment]
Not a problem at all! Thanks for using textAngular

**Comment by darkmavis1980** [comment]
Sorry guys, just updated to version 1.4.4 and I still have the same issue
![screen shot 2015-09-15 at 13 51 39](https://cloud.githubusercontent.com/assets/2980681/9876839/000086b2-5bb1-11e5-8901-165ac720bd6d.png)

**Comment by pbassut** [comment]
@darkmavis1980 We're on 1.4.5 actually.

**Comment by darkmavis1980** [comment]
@pbassut  ah ok, bower was still getting the 1.4.4 after a cache clean, but now it's working correctly and it's getting the 1.4.5

**Comment by pbassut** [comment]
@darkmavis1980 Sweet!
